# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arbsort < Formula
  desc "POEditor JSON to Flutter ARB converter."
  homepage "https://github.com/leancodepl/arbsort"
  version "0.1.0"

  on_macos do
    url "https://github.com/leancodepl/arbsort/releases/download/v0.1.0/arbsort_0.1.0_darwin_all.tar.gz"
    sha256 "b38b95e3e8d7eeb0cc24f2de74221bd4beddf1525c8b27d51ec2f40c2e4e6cef"

    def install
      bin.install "arbsort"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/leancodepl/arbsort/releases/download/v0.1.0/arbsort_0.1.0_linux_amd64.tar.gz"
      sha256 "7280699ec82909eef8c2432705c35ecd5f306144d0a12ecee4314e2b33abea4c"

      def install
        bin.install "arbsort"
      end
    end
  end
end
